blank_issues_enabled: false
contact_links:
  - name: Report Security Concern
    url: https://www.heroku.com/policy/security
    about: If you are a Heroku customer and you would like to report a vulnerability or have a security concern regarding Heroku please email security@salesforce.com